// Single entry point for the PRISM backend.
//
//   NEXT_PUBLIC_PRISM_API_MODE=mock   committed demo fixtures, no backend
//   NEXT_PUBLIC_PRISM_API_MODE=http   the FastAPI service
//
// Mock fixtures are generated by running the real inference stack
// (scripts/generate_demo_fixtures.py), so both modes share the same types and
// the same value shapes.
//
// Don't call fetch directly elsewhere, and don't import fixtures outside here.

import type {
  ModelStatusResponse,
  WebsitePMOSProfileResponse,
} from '@/types/api'

import controlFixture from './demo/control.json'
import demoIndex from './demo/index.json'
import mayaFixture from './demo/maya.json'
import sarahFixture from './demo/sarah.json'

export type ApiMode = 'mock' | 'http'

/** Thrown for any non-2xx response, carrying enough to render a real message. */
export class ApiError extends Error {
  readonly status: number
  readonly detail: unknown

  constructor(message: string, status: number, detail?: unknown) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.detail = detail
  }

  /** True when the backend is up but this capability is deliberately gated. */
  get isUnavailable(): boolean {
    return this.status === 503
  }
}

const DEFAULT_BASE_URL = 'http://localhost:8000'

export function apiMode(): ApiMode {
  const configured = process.env.NEXT_PUBLIC_PRISM_API_MODE
  // Default to mock so an unconfigured checkout shows the demo instead of a
  // network error.
  return configured === 'http' ? 'http' : 'mock'
}

export function apiBaseUrl(): string {
  return process.env.NEXT_PUBLIC_PRISM_API_URL || DEFAULT_BASE_URL
}

// -- demo fixtures ---------------------------------------------------------

export interface DemoFixture {
  key: string
  display_name: string
  summary: string
  exercises: string[]
  notes: string[]
  response: WebsitePMOSProfileResponse
}

// Via `unknown`: TS widens imported JSON to `string` where the contract has a
// literal union, so a direct cast trips the overlap check under `strict`.
const FIXTURES: Record<string, DemoFixture> = {
  sarah: sarahFixture as unknown as DemoFixture,
  control: controlFixture as unknown as DemoFixture,
  maya: mayaFixture as unknown as DemoFixture,
}

export interface DemoSummary {
  key: string
  display_name: string
  summary: string
  evidence_level: string
  score_available: boolean
}

export function demoPatients(): DemoSummary[] {
  return demoIndex as unknown as DemoSummary[]
}

/** The demo patient served in mock mode when a caller does not name one. */
export const DEFAULT_DEMO_PATIENT = 'sarah'

function fixtureFor(patientId: string): DemoFixture {
  // Accept either the demo key ("sarah") or the patient id ("demo-sarah") so a
  // URL carrying a real patient id still resolves in mock mode.
  const key = patientId.replace(/^demo-/, '')
  return FIXTURES[key] ?? FIXTURES[DEFAULT_DEMO_PATIENT]
}

// -- mock responses --------------------------------------------------------

/** Model status in mock mode, matching the real service's gating exactly. */
const MOCK_MODEL_STATUS: ModelStatusResponse = {
  schema_version: '1.0.0',
  static_clinical: {
    available: true,
    trained: true,
    persisted: true,
    validated_for_inference: true,
    version: 'static-clinical-0.1.0',
    implementation: 'trained_logistic',
  },
  temporal_state: {
    available: true,
    trained: true,
    persisted: true,
    validated_for_inference: true,
    version: 'temporal-state-v1',
    implementation: 'target_specific_v1',
  },
  // Mirrors the real gate — the demo shouldn't imply imaging works.
  ovarian_ultrasound: {
    available: false,
    trained: true,
    persisted: true,
    validated_for_inference: false,
    version: 'ultrasound-usova3d-3d-v1',
    implementation: 'trained_unet',
    reason:
      'Ovary segmentation head requires correction and held-out end-to-end evaluation. ' +
      'A checkpoint exists and loads, but its reported follicle Dice is oracle-assisted ' +
      'and is not a deployable patient result.',
  },
  calibration: { available: true, method: 'platt_scaling', note: null },
  warnings: [],
}

function mockResponse(path: string, init?: RequestInit): unknown {
  if (path === '/api/v1/health') return { status: 'ok' }
  if (path === '/api/v1/models/status') return MOCK_MODEL_STATUS

  if (path.startsWith('/api/v1/patients/infer')) {
    if (path.endsWith('/ultrasound')) {
      throw new ApiError('Ultrasound inference is not available.', 503, {
        reason: MOCK_MODEL_STATUS.ovarian_ultrasound.reason,
        validated_for_inference: false,
      })
    }

    const body = init?.body ? JSON.parse(String(init.body)) : {}
    const fixture = fixtureFor(String(body.patient_id ?? DEFAULT_DEMO_PATIENT))

    if (path.endsWith('/temporal')) {
      // Temporal alone never yields a whole-patient score — same as the real
      // service.
      return {
        ...fixture.response,
        pmos_assessment: {
          available: false,
          evidence_level: 'not_available',
          raw_model_score: null,
          calibrated_model_score: null,
          calibrated: false,
          unavailable_reason:
            'The learned static clinical head did not run, so no whole-patient ' +
            'PMOS evidence score is available.',
        },
      }
    }
    return fixture.response
  }

  if (path === '/api/v1/intake/schema') {
    // Mock mode cannot reach the registry, so the form is unavailable rather
    // than served from a hand-copied field list that would drift from it.
    throw new ApiError(
      'The intake form needs the live API. Set NEXT_PUBLIC_PRISM_API_MODE=http.',
      503,
      { reason: 'Intake field definitions come from the backend variable registry.' },
    )
  }

  if (path.startsWith('/api/v1/events')) return []

  if (path.startsWith('/api/v1/jobs/')) {
    const kind = path.split('/')[4] ?? 'documents'
    return {
      job_id: `${kind}-mock`,
      kind,
      patient_id: 'demo',
      status: 'unavailable',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      reason:
        kind === 'ultrasound'
          ? MOCK_MODEL_STATUS.ovarian_ultrasound.reason
          : `${kind} extraction is not connected to this service.`,
      result: null,
    }
  }

  throw new ApiError(`No mock is defined for ${path}`, 501)
}

// -- the client ------------------------------------------------------------

/** One call, either mode. Mock resolves synchronously but still returns a promise. */
export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  if (apiMode() === 'mock') {
    return mockResponse(path, init) as T
  }

  let response: Response
  try {
    response = await fetch(`${apiBaseUrl()}${path}`, {
      ...init,
      headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) },
    })
  } catch (cause) {
    // Transport failure, not a rejected request — the UI wording differs.
    throw new ApiError(
      `Could not reach the PRISM API at ${apiBaseUrl()}.`,
      0,
      cause,
    )
  }

  if (!response.ok) {
    let detail: unknown
    try {
      detail = await response.json()
    } catch {
      detail = await response.text().catch(() => undefined)
    }
    throw new ApiError(
      `${init?.method ?? 'GET'} ${path} failed with ${response.status}.`,
      response.status,
      detail,
    )
  }

  if (response.status === 204) return undefined as T
  return (await response.json()) as T
}

export function apiPost<T>(path: string, body: unknown): Promise<T> {
  return apiFetch<T>(path, { method: 'POST', body: JSON.stringify(body) })
}
