/**
 * Synthetic demonstration data for PRISM prototype.
 * All data is fictional. No real patient information.
 */

import type {
  PatientProfile,
  HormonalHealthEvent,
  PhenotypeDomain,
  ProfileSimilarity,
  StabilityReport,
  TemporalState,
  ProcessingJob,
} from '@/types'

export const DEMO_NOTICE = 'Synthetic demonstration profile — Maya Chen'

export const MOCK_PATIENT_PROFILE: PatientProfile = {
  patientId: 'demo-maya-chen-001',
  displayName: 'Maya Chen',
  lastUpdated: '2026-07-17T14:32:00Z',
  profileCompleteness: 0.62,
  evidenceQuality: 'moderate',
  confirmedCount: 11,
  awaitingCount: 6,
  conflictCount: 2,
  missingHighValueCount: 4,
}

export const MOCK_EVENTS: HormonalHealthEvent[] = [
  // Lab results
  {
    eventId: 'evt-lab-001',
    patientId: 'demo-maya-chen-001',
    variableName: 'Anti-Müllerian Hormone',
    canonicalVariableCode: 'AMH',
    value: 7.2,
    unit: 'ng/mL',
    observedAt: '2026-05-10T09:00:00Z',
    modality: 'lab',
    provenance: 'document_extracted',
    extractionConfidence: 0.97,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    sourceFileId: 'doc-lab-report-may-2026',
    sourcePage: 2,
    evidenceText: 'AMH: 7.2 ng/mL (Reference: 1.0–3.5 ng/mL)',
    parserVersion: '0.4.1',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-lab-002',
    patientId: 'demo-maya-chen-001',
    variableName: 'Luteinizing Hormone',
    canonicalVariableCode: 'LH',
    value: 12.4,
    unit: 'mIU/mL',
    observedAt: '2026-05-10T09:00:00Z',
    modality: 'lab',
    provenance: 'document_extracted',
    extractionConfidence: 0.95,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    sourceFileId: 'doc-lab-report-may-2026',
    sourcePage: 2,
    evidenceText: 'LH: 12.4 mIU/mL (Day 3)',
    parserVersion: '0.4.1',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-lab-003',
    patientId: 'demo-maya-chen-001',
    variableName: 'Follicle-Stimulating Hormone',
    canonicalVariableCode: 'FSH',
    value: 5.1,
    unit: 'mIU/mL',
    observedAt: '2026-05-10T09:00:00Z',
    modality: 'lab',
    provenance: 'document_extracted',
    extractionConfidence: 0.95,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    sourceFileId: 'doc-lab-report-may-2026',
    sourcePage: 2,
    evidenceText: 'FSH: 5.1 mIU/mL (Day 3) — LH:FSH ratio 2.4',
    parserVersion: '0.4.1',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-lab-004',
    patientId: 'demo-maya-chen-001',
    variableName: 'Total Testosterone',
    canonicalVariableCode: 'TESTO_TOTAL',
    value: 68,
    unit: 'ng/dL',
    observedAt: '2026-05-10T09:00:00Z',
    modality: 'lab',
    provenance: 'document_extracted',
    extractionConfidence: 0.93,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: true,
    sourceFileId: 'doc-lab-report-may-2026',
    sourcePage: 3,
    evidenceText: 'Testosterone, Total: 68 ng/dL (Upper normal range; clinical significance uncertain)',
    parserVersion: '0.4.1',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-lab-005',
    patientId: 'demo-maya-chen-001',
    variableName: 'Fasting Insulin',
    canonicalVariableCode: 'INSULIN_FASTING',
    value: null,
    unit: 'µIU/mL',
    observedAt: '2026-05-10T09:00:00Z',
    modality: 'lab',
    provenance: 'document_extracted',
    extractionConfidence: 0,
    confirmationStatus: 'not_required',
    missingnessStatus: 'not_collected',
    negated: false,
    historical: false,
    uncertain: false,
    sourceFileId: 'doc-lab-report-may-2026',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-lab-006',
    patientId: 'demo-maya-chen-001',
    variableName: 'Sex Hormone Binding Globulin',
    canonicalVariableCode: 'SHBG',
    value: null,
    unit: 'nmol/L',
    observedAt: '2026-05-10T09:00:00Z',
    modality: 'lab',
    provenance: 'document_extracted',
    extractionConfidence: 0,
    confirmationStatus: 'not_required',
    missingnessStatus: 'not_collected',
    negated: false,
    historical: false,
    uncertain: false,
    sourceFileId: 'doc-lab-report-may-2026',
    schemaVersion: '0.1.0-demo',
  },
  // Cycle data
  // canonical_variable_code reference:
  //   cycle_length     = days from one menses onset to the next (~28–52 days)
  //   menses_duration  = days of active bleeding within one cycle (~3–7 days)
  // Never conflate the two: the static encoder's scaler for menses_duration
  // has mean 4.94 — sending a 52-day cycle_length into that slot inverts the score.
  {
    eventId: 'evt-cycle-001',
    patientId: 'demo-maya-chen-001',
    variableName: 'Cycle Length',
    canonicalVariableCode: 'cycle_length',
    value: 52,
    unit: 'days',
    observedAt: '2026-06-15T00:00:00Z',
    modality: 'cycle',
    provenance: 'patient_confirmed',
    extractionConfidence: 0.88,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Cycle logged from Apr 24 – Jun 15 (52 days)',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-cycle-002',
    patientId: 'demo-maya-chen-001',
    variableName: 'Cycle Length',
    canonicalVariableCode: 'cycle_length',
    value: 28,
    unit: 'days',
    observedAt: '2026-06-15T00:00:00Z',
    modality: 'document',
    provenance: 'document_extracted',
    extractionConfidence: 0.71,
    confirmationStatus: 'awaiting_patient_confirmation',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: true,
    sourceFileId: 'doc-intake-form-2024',
    sourcePage: 1,
    evidenceText: 'Patient reports cycles "approximately every 4 weeks" on 2024 intake form — conflicts with recent logged data.',
    parserVersion: '0.4.1',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-cycle-003',
    patientId: 'demo-maya-chen-001',
    variableName: 'Menses Duration',
    canonicalVariableCode: 'menses_duration',
    value: 5,
    unit: 'days',
    observedAt: '2026-06-15T00:00:00Z',
    modality: 'cycle',
    provenance: 'patient_confirmed',
    extractionConfidence: 0.95,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Patient reports bleeding for 5 days per cycle',
    schemaVersion: '0.1.0-demo',
  },
  // Symptoms
  {
    eventId: 'evt-sym-001',
    patientId: 'demo-maya-chen-001',
    variableName: 'Acne',
    canonicalVariableCode: 'SYM_ACNE',
    value: 'moderate',
    observedAt: '2026-07-01T00:00:00Z',
    modality: 'symptom',
    provenance: 'patient_confirmed',
    extractionConfidence: 1.0,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Self-reported: moderate acne, primarily jawline and chin, worsening pre-menstrually',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-sym-002',
    patientId: 'demo-maya-chen-001',
    variableName: 'Hirsutism',
    canonicalVariableCode: 'SYM_HIRSUTISM',
    value: 'mild',
    observedAt: '2026-07-01T00:00:00Z',
    modality: 'symptom',
    provenance: 'patient_confirmed',
    extractionConfidence: 1.0,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Self-reported: mild increased facial hair growth, noticed over past 18 months',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-sym-003',
    patientId: 'demo-maya-chen-001',
    variableName: 'Fatigue',
    canonicalVariableCode: 'SYM_FATIGUE',
    value: 'moderate-severe',
    observedAt: '2026-07-01T00:00:00Z',
    modality: 'symptom',
    provenance: 'patient_confirmed',
    extractionConfidence: 1.0,
    confirmationStatus: 'confirmed',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Self-reported: persistent fatigue, especially in the afternoon; difficulty concentrating',
    schemaVersion: '0.1.0-demo',
  },
  // Wearable data
  {
    eventId: 'evt-wear-001',
    patientId: 'demo-maya-chen-001',
    variableName: 'Resting Heart Rate',
    canonicalVariableCode: 'RHR_BPM',
    value: 74,
    unit: 'bpm',
    observedAt: '2026-07-16T06:00:00Z',
    modality: 'wearable',
    provenance: 'device_measured',
    extractionConfidence: 0.99,
    confirmationStatus: 'not_required',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Fitbit Charge 6 — overnight resting HR average',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-wear-002',
    patientId: 'demo-maya-chen-001',
    variableName: 'Heart Rate Variability',
    canonicalVariableCode: 'HRV_RMSSD',
    value: 38,
    unit: 'ms',
    observedAt: '2026-07-16T06:00:00Z',
    modality: 'wearable',
    provenance: 'device_measured',
    extractionConfidence: 0.92,
    confirmationStatus: 'not_required',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Fitbit HRV (RMSSD) — overnight measurement',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-wear-003',
    patientId: 'demo-maya-chen-001',
    variableName: 'Sleep Duration',
    canonicalVariableCode: 'SLEEP_TOTAL_MIN',
    value: 387,
    unit: 'min',
    observedAt: '2026-07-16T06:00:00Z',
    modality: 'wearable',
    provenance: 'device_measured',
    extractionConfidence: 0.94,
    confirmationStatus: 'not_required',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Total sleep time: 6h 27min (below recommended 7–9h)',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-wear-004',
    patientId: 'demo-maya-chen-001',
    variableName: 'Skin Temperature Deviation',
    canonicalVariableCode: 'SKIN_TEMP_DEV_C',
    value: 0.3,
    unit: '°C',
    observedAt: '2026-07-16T06:00:00Z',
    modality: 'wearable',
    provenance: 'device_measured',
    extractionConfidence: 0.88,
    confirmationStatus: 'not_required',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: false,
    evidenceText: 'Skin temperature deviation from baseline: +0.3°C (may indicate post-ovulatory rise)',
    schemaVersion: '0.1.0-demo',
  },
  // Ultrasound
  {
    eventId: 'evt-us-001',
    patientId: 'demo-maya-chen-001',
    variableName: 'Antral Follicle Count (Right Ovary)',
    canonicalVariableCode: 'AFC_RIGHT',
    value: 10,
    unit: 'follicles',
    observedAt: '2026-05-22T00:00:00Z',
    modality: 'ultrasound',
    provenance: 'model_measured',
    extractionConfidence: 0.81,
    confirmationStatus: 'awaiting_clinician_confirmation',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: true,
    sourceFileId: 'us-image-may-2026-right',
    evidenceText: 'Automated follicle count from 2D ultrasound image — right ovary. Requires qualified review.',
    modelVersion: 'prism-us-seg-v0.2',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-us-002',
    patientId: 'demo-maya-chen-001',
    variableName: 'Antral Follicle Count (Left Ovary)',
    canonicalVariableCode: 'AFC_LEFT',
    value: 8,
    unit: 'follicles',
    observedAt: '2026-05-22T00:00:00Z',
    modality: 'ultrasound',
    provenance: 'model_measured',
    extractionConfidence: 0.81,
    confirmationStatus: 'awaiting_clinician_confirmation',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: true,
    sourceFileId: 'us-image-may-2026-left',
    evidenceText: 'Automated follicle count from 2D ultrasound image — left ovary. Requires qualified review.',
    modelVersion: 'prism-us-seg-v0.2',
    schemaVersion: '0.1.0-demo',
  },
  // Model inferred
  {
    eventId: 'evt-model-001',
    patientId: 'demo-maya-chen-001',
    variableName: 'Estimated Cycle Phase',
    canonicalVariableCode: 'PHASE_ESTIMATE',
    value: 'luteal',
    observedAt: '2026-07-17T00:00:00Z',
    modality: 'model',
    provenance: 'model_inferred',
    extractionConfidence: 0.65,
    confirmationStatus: 'awaiting_patient_confirmation',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: true,
    evidenceText: 'Estimated from skin temperature, HRV trend, and last logged period date. Low-medium certainty due to irregular cycles.',
    modelVersion: 'prism-temporal-v0.3',
    schemaVersion: '0.1.0-demo',
  },
  {
    eventId: 'evt-model-002',
    patientId: 'demo-maya-chen-001',
    variableName: 'Insulin Resistance Risk Score',
    canonicalVariableCode: 'IR_RISK_SCORE',
    value: 0.61,
    observedAt: '2026-07-17T00:00:00Z',
    modality: 'model',
    provenance: 'model_inferred',
    extractionConfidence: 0.58,
    confirmationStatus: 'awaiting_patient_confirmation',
    missingnessStatus: 'observed',
    negated: false,
    historical: false,
    uncertain: true,
    evidenceText: 'Inferred from AMH, LH/FSH ratio, testosterone, and symptom pattern. Missing fasting insulin and SHBG reduce confidence significantly.',
    modelVersion: 'prism-metabolic-v0.1',
    schemaVersion: '0.1.0-demo',
  },
]

export const MOCK_PHENOTYPE_DOMAINS: PhenotypeDomain[] = [
  {
    name: 'Reproductive / Ovulatory',
    key: 'reproductive',
    score: 0.74,
    confidence: 0.71,
    coverage: 0.68,
    supportingEvidence: [
      'Irregular cycles (45–70 days observed)',
      'Elevated AMH (7.2 ng/mL)',
      'Elevated LH:FSH ratio (2.4)',
      'Estimated AFC 18 (model, pending review)',
    ],
    missingVariables: ['Progesterone (Day 21)', 'Estradiol (E2, Day 3)'],
  },
  {
    name: 'Metabolic',
    key: 'metabolic',
    score: 0.52,
    confidence: 0.44,
    coverage: 0.41,
    supportingEvidence: [
      'Fatigue (self-reported, moderate-severe)',
      'Insulin resistance risk score 0.61 (model-inferred)',
    ],
    missingVariables: ['Fasting insulin', 'SHBG', 'Fasting glucose', 'HOMA-IR'],
  },
  {
    name: 'Androgenic',
    key: 'androgenic',
    score: 0.61,
    confidence: 0.63,
    coverage: 0.58,
    supportingEvidence: [
      'Total testosterone borderline elevated (68 ng/dL)',
      'Self-reported hirsutism (mild)',
      'Self-reported acne (moderate, jawline pattern)',
    ],
    missingVariables: ['Free testosterone', 'DHEA-S', 'SHBG (needed for free T calculation)'],
  },
  {
    name: 'Ovarian Morphology',
    key: 'morphology',
    score: 0.68,
    confidence: 0.81,
    coverage: 0.55,
    supportingEvidence: [
      'AFC right: 10 (automated, pending clinician review)',
      'AFC left: 8 (automated, pending clinician review)',
      'Total estimated follicles: 18',
    ],
    missingVariables: ['Ovarian volume', 'Follicle distribution description', 'Clinician-reviewed AFC'],
  },
  {
    name: 'Thyroid',
    key: 'thyroid',
    score: 0.12,
    confidence: 0.28,
    coverage: 0.15,
    supportingEvidence: [],
    missingVariables: ['TSH', 'Free T4', 'Thyroid antibodies (TPO, TgAb)'],
  },
  {
    name: 'Symptom Burden',
    key: 'symptoms',
    score: 0.58,
    confidence: 0.82,
    coverage: 0.72,
    supportingEvidence: [
      'Acne (moderate, jawline, pre-menstrual worsening)',
      'Hirsutism (mild, 18 months)',
      'Fatigue (moderate-severe, persistent)',
      'Irregular cycles (patient-confirmed)',
    ],
    missingVariables: ['Mood disorder screening (PHQ-9)', 'Sleep quality questionnaire', 'Pain mapping'],
  },
]

export const MOCK_PROFILE_SIMILARITIES: ProfileSimilarity[] = [
  { label: 'Metabolic-leaning pattern', probability: 0.38, stability: 0.61 },
  { label: 'Reproductive/LH-AMH-driven pattern', probability: 0.31, stability: 0.54 },
  { label: 'Mixed androgenic-reproductive pattern', probability: 0.19, stability: 0.42 },
  { label: 'Indeterminate / insufficient data', probability: 0.12, stability: 0.88 },
]

export const MOCK_STABILITY_REPORT: StabilityReport = {
  overallStability: 'moderate',
  bootstrapAgreement: 0.61,
  subtypeFlipRate: 0.28,
  sensitiveVariables: [
    { variable: 'AMH', flipRateWithout: 0.21 },
    { variable: 'Fasting Glucose', flipRateWithout: 0.08 },
    { variable: 'Total Testosterone', flipRateWithout: 0.06 },
    { variable: 'Cycle Length', flipRateWithout: 0.05 },
  ],
  abstained: false,
}

export const MOCK_TEMPORAL_STATE: TemporalState = {
  date: '2026-07-17',
  cycleDay: undefined,
  phaseDistribution: {
    menstrual: 0.03,
    follicular: 0.14,
    periOvulatory: 0.18,
    luteal: 0.65,
  },
  coverage: 0.58,
  uncertainty: 'moderate',
  missingStreams: ['LH surge (urine or serum)', 'Progesterone (serum)', 'Estradiol (serum)', 'CGM'],
}

export function createMockJob<T>(
  type: 'speech' | 'document' | 'ultrasound' | 'temporal',
  result?: T
): ProcessingJob<T> {
  return {
    id: `job-${type}-${Date.now()}`,
    type,
    stage: result ? 'completed' : 'queued',
    progress: result ? 100 : 0,
    message: result ? 'Processing complete' : 'Job queued',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    result,
  }
}
