'use client'

// The printable summary a patient brings to an appointment.
//
// This leaves the app and gets handed to a clinician who didn't watch it being
// made. Every value comes from the actual report, there is no fallback content,
// and with no report it prints a page saying so rather than a template with
// plausible-looking numbers.

import {
  axisLabel,
  axisStatusLabel,
  evidenceLabel,
  formatCoverage,
  formatScore,
  formatZScore,
  humanizeCode,
  orderedDomains,
  phenotypeVerdict,
} from '@/lib/present'
import { type AskDoctorItem, formatAnswersForSummary } from '@/lib/askDoctor'
import type { WebsitePMOSProfileResponse } from '@/types/api'

const PAGE: React.CSSProperties = {
  fontFamily: 'Georgia, serif',
  color: '#111',
  padding: '40px',
  maxWidth: '700px',
  margin: '0 auto',
}

const DISCLAIMER: React.CSSProperties = {
  marginTop: '8px',
  padding: '8px 12px',
  background: '#fef3c7',
  border: '1px solid #d97706',
  borderRadius: '6px',
  fontSize: '11px',
  color: '#92400e',
}

export default function VisitSummary({
  report,
  answers,
  askDoctorItems,
}: {
  report: WebsitePMOSProfileResponse | null
  answers?: Record<string, string | boolean | undefined>
  askDoctorItems?: AskDoctorItem[]
}) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  // No report, no document.
  if (!report) {
    return (
      <div className="print-page" style={PAGE}>
        <h1 style={{ fontSize: '22px', fontWeight: 'bold', margin: 0 }}>
          Hormonal Health Summary
        </h1>
        <p style={{ fontSize: '13px', color: '#555', marginTop: '4px' }}>Prepared: {today}</p>
        <div style={DISCLAIMER}>
          <strong>No assessment has been run.</strong> This document is intentionally empty.
          Complete the intake form in PRISM and run an analysis before printing a summary.
        </div>
      </div>
    )
  }

  const assessment = report.pmos_assessment
  const verdict = phenotypeVerdict(report)
  const axes = Object.entries(report.rotterdam_axes ?? {})
  const domains = orderedDomains(report.phenotype?.domain_scores)
  const generated = new Date().toLocaleString()

  return (
    <div className="print-page" style={PAGE}>
      <div style={{ borderBottom: '2px solid #333', paddingBottom: '16px', marginBottom: '24px' }}>
        <h1 style={{ fontSize: '22px', fontWeight: 'bold', margin: 0 }}>
          Hormonal Health Summary
        </h1>
        <p style={{ fontSize: '13px', color: '#555', marginTop: '4px' }}>
          Prepared: {today} · Patient ID: {report.patient_id} · Generated by PRISM (Research
          Prototype)
        </p>
        <div style={DISCLAIMER}>
          <strong>Disclaimer:</strong> This document was generated by a research prototype and{' '}
          <strong>does not constitute a medical diagnosis</strong>. Values shown are self-reported
          or extracted from uploaded documents and have not been independently verified. All
          observations require clinical evaluation.
        </div>
      </div>

      {answers && Object.keys(answers).length > 0 && (() => {
        const rows = formatAnswersForSummary(answers)
        return rows.length > 0 ? (
          <Section title="What you reported">
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
              <tbody>
                {rows.map(({ label, value }) => (
                  <tr key={label} style={{ borderBottom: '1px solid #f0f0f0' }}>
                    <td style={{ padding: '3px 8px 3px 0', color: '#555', width: '55%' }}>{label}</td>
                    <td style={{ padding: '3px 0', fontWeight: 600 }}>{value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Section>
        ) : null
      })()}

      {askDoctorItems && askDoctorItems.length > 0 && (
        <Section title="Questions and tests to discuss with your doctor">
          <p style={{ fontSize: '11px', color: '#555', marginBottom: '8px' }}>
            The following tests and conversations would allow PRISM to reach more conclusive findings.
            Bring this list to your appointment.
          </p>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid #ccc' }}>
                <th style={{ textAlign: 'left', padding: '4px 8px 4px 0', color: '#444', fontWeight: 'bold' }}>Ask your doctor to</th>
                <th style={{ textAlign: 'left', padding: '4px 8px', color: '#444', fontWeight: 'bold' }}>Why it matters</th>
              </tr>
            </thead>
            <tbody>
              {askDoctorItems.map((item, i) => (
                <tr key={i} style={{ borderBottom: '1px solid #eee' }}>
                  <td style={{ padding: '5px 8px 5px 0', verticalAlign: 'top', fontWeight: 600 }}>
                    <span style={{
                      display: 'inline-block',
                      marginRight: '6px',
                      padding: '1px 5px',
                      borderRadius: '4px',
                      fontSize: '10px',
                      background: item.urgency === 'high' ? '#fef2f2' : item.urgency === 'medium' ? '#fffbeb' : '#f9fafb',
                      color: item.urgency === 'high' ? '#b91c1c' : item.urgency === 'medium' ? '#92400e' : '#6b7280',
                    }}>
                      {item.urgency}
                    </span>
                    {item.question}
                  </td>
                  <td style={{ padding: '5px 8px', verticalAlign: 'top', color: '#555' }}>{item.why}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>
      )}

      <Section title="PMOS-related evidence">
        {assessment.available ? (
          <>
            <Row label="Evidence level" value={evidenceLabel(assessment.evidence_level)} />
            <Row
              label="Model score"
              value={`${formatScore(
                assessment.calibrated_model_score ?? assessment.raw_model_score,
              )}${assessment.calibrated ? ' (calibrated)' : ' (uncalibrated)'}`}
            />
            <Row label="Source" value="Static-clinical branch" />
            {/* The score can't be weighed without knowing how much was observed. */}
            <Row
              label="Observed model inputs"
              value={formatCoverage(assessment.feature_coverage)}
            />
            <Row label="Data sources contributing" value={formatCoverage(report.modality_coverage)} />
            <p style={{ fontSize: '11px', color: '#555', marginTop: '8px' }}>
              This is not a probability that the patient has PMOS. It is a score from a model
              fitted on a single-site cross-sectional cohort.
            </p>
          </>
        ) : (
          <p style={{ fontSize: '12px' }}>
            No whole-profile model score was calculated.{' '}
            {assessment.unavailable_reason ?? ''}
          </p>
        )}
      </Section>

      <Section title="Rotterdam-axis assessment">
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid #ccc' }}>
              {['Axis', 'Status', 'Basis'].map((h) => (
                <th
                  key={h}
                  style={{ textAlign: 'left', padding: '4px 8px', fontWeight: 'bold', color: '#444' }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {axes.map(([key, axis]) => (
              <tr key={key} style={{ borderBottom: '1px solid #eee' }}>
                <td style={{ padding: '4px 8px' }}>{axisLabel(key)}</td>
                <td style={{ padding: '4px 8px' }}>{axisStatusLabel(axis.status)}</td>
                <td style={{ padding: '4px 8px', color: '#555' }}>
                  {axis.status === 'not_assessable'
                    ? `Not assessed — ${(axis.missing_evidence ?? []).slice(0, 3).map(humanizeCode).join(', ') || 'no evidence available'}`
                    : (axis.supporting_evidence ?? []).slice(0, 2).join('; ') || '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {report.androgenic_evidence_source === 'symptoms_only' && (
          <p style={{ fontSize: '11px', color: '#555', marginTop: '8px' }}>
            <strong>Note:</strong> androgenic evidence rests on reported symptoms only.
            Biochemical androgen measurements were unavailable.
          </p>
        )}
      </Section>

      <Section title="Phenotype domain scores">
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid #ccc' }}>
              {['Domain', 'Score (cohort z)', 'Coverage', 'Evidence'].map((h) => (
                <th
                  key={h}
                  style={{ textAlign: 'left', padding: '4px 8px', fontWeight: 'bold', color: '#444' }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {domains.map(([key, domain]) => (
              <tr key={key} style={{ borderBottom: '1px solid #eee' }}>
                <td style={{ padding: '4px 8px' }}>{domain.label ?? humanizeCode(key)}</td>
                <td style={{ padding: '4px 8px' }}>
                  {domain.available ? formatZScore(domain.score) : 'Not assessed'}
                </td>
                <td style={{ padding: '4px 8px' }}>{formatCoverage(domain.coverage)}</td>
                <td style={{ padding: '4px 8px', color: '#555' }}>
                  {domain.evidence_source ?? '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <p style={{ fontSize: '11px', color: '#555', marginTop: '8px' }}>
          Scores are standard deviations from the training-cohort mean, not percentages.
        </p>
      </Section>

      <Section title="Phenotype pattern">
        <p style={{ fontSize: '12px' }}>{verdict.headline}</p>
        {verdict.body && (
          <p style={{ fontSize: '11px', color: '#555', marginTop: '4px' }}>{verdict.body}</p>
        )}
        <p style={{ fontSize: '11px', color: '#555', marginTop: '4px' }}>
          Phenotype profiles are exploratory similarities to patterns described in the literature,
          not validated clinical subtypes.
        </p>
      </Section>

      {(report.missing_evidence?.length ?? 0) > 0 && (
        <Section title="Not available for this assessment">
          <p style={{ fontSize: '12px' }}>
            {report.missing_evidence!.map(humanizeCode).join(', ')}
          </p>
          <p style={{ fontSize: '11px', color: '#555', marginTop: '4px' }}>
            These were not measured or not provided. Their absence limits which conclusions could
            be reached; it is not itself a finding.
          </p>
        </Section>
      )}

      <Section title="Provenance">
        <Row label="Report ID" value={report.report_id} />
        <Row label="Generated" value={generated} />
        <Row label="Schema version" value={report.schema_version ?? '—'} />
        <Row
          label="Models used"
          value={
            Object.entries(report.provenance?.model_versions ?? {})
              .map(([name, version]) => `${humanizeCode(name)} ${version}`)
              .join('; ') || '—'
          }
        />
        <Row
          label="Rule-based components"
          value={(report.rule_based_components_used ?? []).join('; ') || '—'}
        />
        <p style={{ fontSize: '11px', color: '#555', marginTop: '8px' }}>
          Cross-modal evidence is combined by transparent rules, not a jointly trained fusion
          model.
        </p>
      </Section>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '22px' }}>
      <h2
        style={{
          fontSize: '14px',
          fontWeight: 'bold',
          borderBottom: '1px solid #ddd',
          paddingBottom: '4px',
          marginBottom: '8px',
        }}
      >
        {title}
      </h2>
      {children}
    </div>
  )
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', padding: '3px 0' }}>
      <span style={{ color: '#555' }}>{label}</span>
      <span style={{ fontWeight: 600 }}>{value}</span>
    </div>
  )
}
