#!/usr/bin/env python3
"""Build a model card from a completed experiment directory.

Writes ``artifacts/model_cards/<model_name>.md``. It deliberately does **not**
touch the top-level ``MODEL_CARD.md`` — that file states what the project claims,
and a generated file cannot review its own claims.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts._cli import make_parser, resolve_output_dir  # noqa: E402

NON_DIAGNOSTIC = (
    "This model is a research artifact. It does not diagnose any condition, "
    "does not provide medical advice, and is not validated for clinical use."
)

DEFAULT_OUT_OF_SCOPE = [
    "Diagnosis of PCOS or any other condition",
    "Screening, triage, or risk stratification of real patients",
    "Guiding, ordering, or withholding any clinical test or treatment",
    "Any deployment where a person is affected by the output",
]


def _load(path: Path) -> dict:
    return json.loads(path.read_text()) if path.exists() else {}


def _fmt_metrics(metrics: dict, stds: dict) -> str:
    if not metrics:
        return "_No aggregate metrics recorded._"
    lines = ["| Metric | Value |", "|:--|--:|"]
    for name, value in metrics.items():
        std = stds.get(name)
        cell = f"{value:.4f}" + (f" ± {std:.4f}" if isinstance(std, (int, float)) else "")
        lines.append(f"| {name} | {cell} |")
    return "\n".join(lines)


def build(experiment_dir: Path, output_dir: Path) -> Path:
    metrics = _load(experiment_dir / "metrics.json")
    if not metrics:
        raise SystemExit(f"No metrics.json in {experiment_dir}. Run the experiment first.")

    card = _load(experiment_dir / "model_card.json")
    environment = _load(experiment_dir / "environment.json")

    model_name = metrics.get("model", "unknown_model")
    experiment_id = metrics.get("experiment_id", experiment_dir.name)
    commit_file = experiment_dir / "git_commit.txt"
    commit = commit_file.read_text().strip() if commit_file.exists() else "unknown"

    limitations = card.get("limitations") or metrics.get("limitations") or []
    out_of_scope = card.get("out_of_scope_uses") or DEFAULT_OUT_OF_SCOPE

    body = (
        f"""# Model card — `{model_name}`

_Generated by `scripts/build_model_card.py` from `{experiment_dir}`._
_Do not edit by hand; edit the experiment or the generator._

> {NON_DIAGNOSTIC}

## Identity

| | |
|:--|:--|
| Model | `{model_name}` |
| Experiment | `{experiment_id}` |
| Model version | {card.get("model_version", "0.1.0")} |
| Git commit | `{commit}` |
| Python | {environment.get("python_version", "unknown")} |

## Intended use

{card.get("intended_use", "Research use: methods development for hormonal-health modeling.")}

## Out-of-scope uses

"""
        + "\n".join(f"- {use}" for use in out_of_scope)
        + f"""

## Data

| | |
|:--|:--|
| Dataset version | `{metrics.get("dataset_version", "unknown")}` |
| Target | `{metrics.get("target", "unknown")}` |
| Split strategy | {metrics.get("split_strategy", "unknown")} |
| Seeds | {", ".join(str(s) for s in metrics.get("seeds", [])) or "unspecified"} |
| Folds evaluated | {len(metrics.get("fold_metrics", []))} |

Split manifest: `{metrics.get("split_manifest", "—")}`
Feature manifest: `{metrics.get("feature_manifest", "—")}`

## Performance

{_fmt_metrics(metrics.get("aggregate_metrics", {}), metrics.get("aggregate_metrics_std", {}))}

### Calibration

{
            _fmt_metrics(
                {
                    k: v
                    for k, v in (metrics.get("calibration_metrics") or {}).items()
                    if isinstance(v, (int, float))
                },
                {},
            )
        }

Discrimination without calibration is not sufficient to interpret a probability.

## Limitations

"""
        + (
            "\n".join(f"- {item}" for item in limitations)
            if limitations
            else "- Not stated by the experiment. This is itself a limitation."
        )
        + """

## Ethical considerations

"""
        + "\n".join(
            f"- {item}"
            for item in card.get(
                "ethical_considerations",
                [
                    "Performance in populations under-represented in training data is unknown.",
                    "Symptom-based androgenic scoring is not biochemical hyperandrogenism and "
                    "its error is unequal across ancestries.",
                ],
            )
        )
        + f"""

## Reproduction

```bash
git checkout {commit}
python scripts/<training_script>.py --config {experiment_dir / "config.resolved.yaml"}
```
"""
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{model_name}.md"
    output_path.write_text(body)
    return output_path


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser. Exposed so the CLI contract test can inspect it."""
    parser = make_parser(description=__doc__)
    parser.add_argument(
        "--experiment-dir",
        type=Path,
        required=True,
        help="An artifact directory written by one of the training scripts.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Destination directory for the generated card. Falls back to "
            "$PRISM_ARTIFACT_ROOT, then artifacts/model_cards."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    output_dir = resolve_output_dir({"output": {"dir": "artifacts/model_cards"}}, args.output_dir)
    path = build(args.experiment_dir, output_dir)
    print(f"Wrote {path}")
    print("Top-level MODEL_CARD.md is human-reviewed and was not modified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
