"""Demo patient inputs.

These are inputs, not outputs. The fixtures the frontend ships come from running
these through the real stack (``scripts/generate_demo_fixtures.py``), so mock
mode shows genuine model output rather than plausible-looking numbers.

Hand-written mock values drift, and a demo built on them shows behaviour the
system doesn't have -- a profile it would never report, an axis "met" on evidence
the rules would reject.

The three cover the states the UI must handle:

* ``sarah``   -- two Rotterdam axes met on symptoms; no androgen assay.
* ``control`` -- regular cycles, no androgenic signs; the low-evidence path.
* ``maya``    -- metabolic-leaning with labs; a different domain mix.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

__all__ = ["DEMO_PATIENTS", "DemoPatient"]


@dataclass(frozen=True)
class DemoPatient:
    """One demo patient's inputs and the story the fixture is meant to tell."""

    key: str
    patient_id: str
    display_name: str
    #: What this profile is for, shown in the demo picker and in DEMO_PATIENTS.md.
    summary: str
    #: Which UI states this fixture is meant to exercise.
    exercises: tuple[str, ...]
    clinical_features: dict[str, Any]
    #: Longitudinal days, generated by the fixture script when `temporal_days` > 0.
    temporal_days: int = 0
    temporal_profile: str = "regular"
    notes: list[str] = field(default_factory=list)


#: Irregular cycles plus cutaneous androgenic signs, no androgen assay.
_SARAH = DemoPatient(
    key="sarah",
    patient_id="demo-sarah",
    display_name="Sarah",
    summary=(
        "Irregular cycles and reported androgenic symptoms, with no androgen "
        "assay drawn. Two Rotterdam axes are met; the third is not assessable."
    ),
    exercises=(
        "symptoms-only androgenic evidence with its qualifier",
        "biochemical androgenic evidence unavailable",
        "ovulatory dysfunction met",
        "polycystic ovarian morphology not assessable",
    ),
    clinical_features={
        "age": 29,
        "bmi": 31.4,
        "weight": 82.0,
        "height": 162.0,
        "cycle_length": 48.0,
        "menses_duration": 6.0,
        "cycle_irregularity": True,
        "hirsutism": True,
        "acne": True,
        "androgenic_alopecia": True,
        "ferriman_gallwey_score": 9.0,
        "luteinizing_hormone": 14.2,
        "follicle_stimulating_hormone": 5.1,
        "anti_mullerian_hormone": 7.8,
    },
    temporal_days=30,
    temporal_profile="irregular",
    notes=[
        "No androgen assay: the biochemical axis must stay not assessable.",
        "No ultrasound: PCOM must stay not assessable rather than 'not met'.",
    ],
)

#: Healthy control, so the low-evidence path gets designed rather than assumed.
_CONTROL = DemoPatient(
    key="control",
    patient_id="demo-control",
    display_name="Priya",
    summary=(
        "Regular cycles, no androgenic signs, unremarkable labs. The "
        "low-evidence path: little is met, and little is missing."
    ),
    exercises=(
        "low evidence level",
        "ovulatory dysfunction not met",
        "no dominant phenotype profile",
    ),
    clinical_features={
        "age": 27,
        "bmi": 22.1,
        "weight": 58.0,
        "height": 162.0,
        "cycle_length": 29.0,
        "menses_duration": 5.0,
        "cycle_irregularity": False,
        "hirsutism": False,
        "acne": False,
        "androgenic_alopecia": False,
        "ferriman_gallwey_score": 2.0,
        "luteinizing_hormone": 5.4,
        "follicle_stimulating_hormone": 6.2,
        "anti_mullerian_hormone": 2.4,
        "fasting_glucose": 86.0,
        "waist_circumference": 74.0,
        "hip_circumference": 96.0,
    },
    temporal_days=30,
    temporal_profile="regular",
    notes=["Included so the low-evidence layout is designed, not an afterthought."],
)

#: Metabolic-leaning with androgens drawn, so the UI can't assume the
#: symptoms-only qualifier is always present.
_MAYA = DemoPatient(
    key="maya",
    patient_id="demo-maya",
    display_name="Maya",
    summary=(
        "Metabolic features with a full lab panel including androgens. "
        "Biochemical evidence is available here, unlike Sarah."
    ),
    exercises=(
        "biochemical androgenic evidence available",
        "metabolic domain assessable",
        "domain coverage varying across domains",
    ),
    clinical_features={
        "age": 34,
        "bmi": 34.8,
        "weight": 94.0,
        "height": 164.0,
        "cycle_length": 38.0,
        "menses_duration": 4.0,
        "cycle_irregularity": True,
        "hirsutism": False,
        "acne": False,
        "skin_darkening": True,
        "weight_gain": True,
        "ferriman_gallwey_score": 3.0,
        "waist_circumference": 102.0,
        "hip_circumference": 112.0,
        "waist_hip_ratio": 0.91,
        "fasting_glucose": 112.0,
        "fasting_insulin": 21.0,
        "hdl_cholesterol": 38.0,
        "triglycerides": 186.0,
        "systolic_blood_pressure": 134.0,
        "diastolic_blood_pressure": 86.0,
        "total_testosterone": 62.0,
        "dheas": 268.0,
        "shbg": 24.0,
        "luteinizing_hormone": 9.1,
        "follicle_stimulating_hormone": 6.0,
        "anti_mullerian_hormone": 5.2,
    },
    temporal_days=0,
    notes=[
        "No temporal data: exercises the 'current state unavailable' path while "
        "the static branch still produces a full report."
    ],
)

DEMO_PATIENTS: tuple[DemoPatient, ...] = (_SARAH, _CONTROL, _MAYA)
